version: "3.8"

services:
  web:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"  
    depends_on:
      - db 
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db/postgres  
    volumes:
      - .:/app  
    networks:
      - app-network

  db:
    image: postgres:15  
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 232425
      POSTGRES_DB: clients
    ports:
      - "5432:5432"  
    networks:
      - app-network
    volumes:
      - pgdata:/var/lib/postgresql/data 

networks:
  app-network:
    driver: bridge

volumes:
  pgdata:
